wandb_version: 1

gnn-out-dim:
  value: 16
gpu-id:
  value: 0
hid-dim:
  value: 16
interval-set:
  value:
  - 1
  - 4
k-hop:
  value: 1
lr:
  value: 0.0001
model-use:
  value: PM25GNN
mt-hid-dim:
  value: 32
seed:
  value: 1
wd:
  value: 0.0001
