wandb_version: 1

gnn-out-dim:
  value: 16
gpu-id:
  value: 0
hid-dim:
  value: 16
interval-set:
  value:
  - 1
  - 4
k-hop:
  value: 1
lr:
  value: 1.0e-05
model-use:
  value: City_GC_GRU
mt-hid-dim:
  value: 16
seed:
  value: 0
wd:
  value: 1.0e-05
